### ISSUE TITLE
Make the candidate parsing more resilient

### ISSUE THREAD

**Issue by strainu** [code4romania/rezultate-vot-api#60]
The candidate parsing code (functions `ExtractCandidatesFromCsv` and `GetCandidates`) assume there are exactly 26 fields before the candidate list starts. This is error-prone and easy to fix, as we know the candidate have a suffix ("-voturi"). Instead of assuming a fixed value, parse the file header and count the fields that do not end with the known suffix.

**Comment by thewindev** [comment]
100% agree. I'll close this without fixing though, because this code will be removed. It was something done quickly to parse the candidates after the results started being published. I'll make another issue more generic for created a parsing mechanism that could be used for more types of elections, not just local.
